[package]
name = "can-sim"
version = "0.1.0"
authors = ["Ueki Masaru <masaru.ueki@itage.co.jp>"]

[dependencies]
tokio = "*"
tokio-timer = "*"
tokio-uds = "*"
futures = "*"
csv = "*"
serde = "*"
serde_derive = "1.0"
